Login + Playlist sync for Homey Media
matjaz/homey-youtube pull request #13
Opened 2017-04-07 23:56 UTC by MarvinSchenkel

Adds login and playlist sync to the youtube app.

Note, nearly processed all your feedback. Don't have that much time, so maybe you can pick up a few things?

2017-04-08 20:39 UTC, matjaz requested changes

2017-04-08 20:39 UTC, matjaz commented on lib/youtube-mp3.js
> +      video: escape(videoUrl)
you shouldn't escape values here.

2017-04-08 20:39 UTC, matjaz commented on locales/nl.json
> +    "apiKey": "API key",
please use same indentation.

2017-04-08 20:39 UTC, matjaz commented on lib/youtube-mp3.js
> +      callback(new Error('Failed to get an MP3-stream. This is most likely because the video is longer than 120 minutes'))
missing return here

2017-04-08 20:39 UTC, matjaz commented on lib/oauth.js
> +    callback(new Error('Could not find an access token for the current user'))
missing return

2017-04-08 20:39 UTC, matjaz commented on lib/media.js
> +        return Homey.error(err)
return not needed

2017-04-08 20:39 UTC, matjaz commented on lib/youtube-mp3.js
> +    callback(null, response.link, response.length)
please convert this to `callback(err, val)` so
```
callback(null, {link, length})
```

2017-04-08 20:39 UTC, matjaz commented on lib/media.js
> +    // track.duration = duration
remove if not needed

2017-04-08 20:39 UTC, matjaz commented on lib/media.js
> +                  callback(err, [])
we should reject promise or `return` here. I recommend reject and handle rejection in `Promise.all` below.

2017-04-08 20:39 UTC, matjaz commented on lib/media.js
> +          var playlistItems = result.items.map(function (item) {
`var playlistItems = result.items.map(exports.parseTrack)`

2017-04-17 01:44 UTC, MarvinSchenkel commented
Implemented your review changes!

2017-04-17 18:03 UTC, matjaz approved these changes

2017-04-17 18:03 UTC, merged